#!/usr/bin/env node
// Embeds infra/hermes/*.patch into the server so every build (npm, single
// executable, desktop) can apply them without shipping loose files.
// Run after changing a patch: node scripts/generate-hermes-patches.ts
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";

const repoRoot = NodePath.resolve(import.meta.dirname, "..");
const sourceDir = NodePath.join(repoRoot, "infra/hermes");
const target = NodePath.join(repoRoot, "apps/server/src/hermes/hermesPatchFiles.generated.ts");

const files = NodeFS.readdirSync(sourceDir)
  .filter((name) => name.endsWith(".patch"))
  .toSorted();
const entries = files.map(
  (name) =>
    `  ${JSON.stringify(name)}: ${JSON.stringify(NodeFS.readFileSync(NodePath.join(sourceDir, name), "utf8"))},`,
);

NodeFS.writeFileSync(
  target,
  [
    "// Generated by scripts/generate-hermes-patches.ts from infra/hermes. Do not edit.",
    "export const HERMES_PATCH_FILES: Readonly<Record<string, string>> = {",
    ...entries,
    "};",
    "",
  ].join("\n"),
);
console.log(`Wrote ${files.length} patch(es) to ${NodePath.relative(repoRoot, target)}`);
